site_name: Challenge Bíblico
site_url: https://kiki7766.github.io/bible-mkdocs/
site_author: Peggy Gonzalez (PG)
site_description: >-
  Esta página será dedicada para publicar versos bíblicos mensualmente. 

# Repository
repo_name: bible-mkdocs
repo_url: https://github.com/kiki7766/bible-mkdocs

# Copyrights
copyright: Copyright &copy; 2023 Kiki7766 by Peggy Gonzalez

# Configuration of Personal Page
theme:
  name: material
  icon:
    logo: fontawesome/solid/book-bible
  favicon: assets/fire.jpg
  features:
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    # - toc.integrate 
    - toc.follow 
    # - navigation.top  
    # - navigation.path
    # - navigation.expand
    # - navigation.tabs
    # - navigation.tabs.sticky
    - content.tabs.link
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: light green
      accent: orange #lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Console Lucida


# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox
  - charts
  # - table-reader

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6


# Customization
extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kiki7766
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/kiki7766_pg
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/kiki7766
    - icon: fontawesome/brands/deviantart
      link: https://deviantart.com/kiki7766   
    - icon: fontawesome/brands/discord
      link: https://discord.com/Kiki7766#1421     

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
# Page Tree (FINALLY)
nav:
  - Home: index.md
  - Información Técnica de la Biblia:
    - data/index.md
  - Historial de Lecturas Bíblica Mensuales 2023:
    - m-2023/index.md
    - Enero 2023: m-2023/enero.md
    - Febrero 2023: m-2023/febrero.md  
    - Marzo 2023: m-2023/marzo.md
    - Abril 2023: m-2023/abril.md
    - Mayo 2023: m-2023/mayo.md
    - Junio 2023: m-2023/junio.md
    - Julio 2023: m-2023/julio.md
    - Agosto 2023: m-2023/agosto.md
    - Septiembre 2023: m-2023/septiembre.md
    - Octubre 2023: m-2023/octubre.md
    - Noviembre 2023: m-2023/noviembre.md
    - Diciembre 2023: m-2023/diciembre.md